=== OpenGameBackend/OpenGameBackend/artifacts/module_schema.json
{"type":"object","properties":{"status":{"enum":["beta","coming_soon","end_of_life","maintenance","preview","stable"],"type":"string"},"name":{"description":"The human readable name of the module.","type":"string"},"description":{"description":"A short description of the module.","type":"string"},"icon":{"description":"The [Font Awesome](https://fontawesome.com/icons) icon name of the module.","type":"string"},"tags":{"description":"The tags associated with this module.","type":"array","items":{"type":"string"}},"authors":{"description":"The GitHub handle of the authors of the module.","type":"array","items":{"type":"string"}},"scripts":{"type":"object","additionalProperties":{"$ref":"#/definitions/ScriptConfig"}},"actors":{"type":"object","additionalProperties":{"$ref":"#/definitions/ActorConfig"}},"errors":{"type":"object","additionalProperties":{"$ref":"#/definitions/ErrorConfig"}},"dependencies":{"type":"object","additionalProperties":{"$ref":"#/definitions/DependencyConfig"}},"defaultConfig":{"description":"Default user config.\n\nThe user-provided config will be deep merged with this config."}},"additionalProperties":false,"required":["errors","scripts"],"definitions":{"ScriptConfig":{"type":"object","properties":{"name":{"description":"The human readable name of the script.","type":"string"},"description":{"description":"A short description of the script.","type":"string"},"public":{"description":"If the script can be called from the public HTTP interface.\n\nIf enabled, ensure that authentication & rate limits are configured for\nthis endpoints. See the `user` and `rate_limit` modules.","default":false,"type":"boolean"}},"additionalProperties":false},"ActorConfig":{"type":"object","properties":{"storageAlias":{"description":"Used to keep actor IDs the same in case the actor name changes.\n\n**IMPORTANT** Changing this will effectively unlink all data stored in\nthis actor. Changing it back to the old value will restore the data.","type":"string"}},"additionalProperties":false},"ErrorConfig":{"type":"object","properties":{"name":{"description":"The human readable name of the error.","type":"string"},"description":{"description":"A short description of the error.","type":"string"}},"additionalProperties":false},"DependencyConfig":{"type":"object","additionalProperties":false}},"$schema":"http://json-schema.org/draft-07/schema#"}

=== OpenGameBackend/OpenGameBackend/modules/currency/module.json
{
    "name": "Currency",
    "description": "Track user balances and allow them to deposit and withdraw.",
    "icon": "coin",
    "tags": [
        "economy"
    ],
    "authors": [
        "ABCxFF"
    ],
    "status": "preview",
    "dependencies": {
        "rate_limit": {},
        "users": {}
    },
    "scripts": {
        "deposit": {
            "name": "Deposit"
        },
        "withdraw": {
            "name": "Withdraw"
        },
        "get_balance": {
            "name": "Get Balance"
        },
        "set_balance": {
            "name": "Set Balance"
        },
        "get_balance_by_token": {
            "name": "Get Balance by Token",
            "public": true
        }
    },
    "errors": {
        "invalid_user": {
            "name": "Invalid User"
        },
        "invalid_amount": {
            "name": "Invalid Amount"
        },
        "not_enough_funds": {
            "name": "Not Enough Funds"
        }
    }
}

=== OpenGameBackend/OpenGameBackend/modules/rivet/module.json
{
	"name": "Rivet API",
	"description": "Helper for calling the Rivet API.",
	"icon": "r",
	"tags": [
		"core",
		"api"
	],
	"authors": [
		"NathanFlurry"
	],
	"status": "stable",
	"scripts": {
		"call": {
			"name": "Call",
			"description": "Call a Rivet REST endpoint."
		}
	},
	"errors": {
		"rivet_error": {
			"name": "Rivet Error",
			"description": "An error from the Rivet API."
		}
	},
	"defaultConfig": {
		"apiEndpoint": "https://api.rivet.gg",
		"serviceTokenVariable": "RIVET_SERVICE_TOKEN"
	}
}

=== OpenGameBackend/OpenGameBackend/modules/sms/module.json
{
    "name": "SMS",
    "description": "Send SMS messages using multiple providers.",
    "icon": "envelope",
    "tags": [
        "sms"
    ],
    "authors": [
        "rivet-gg",
        "Blckbrry-Pi"
    ],
    "status": "stable",
    "scripts": {
        "send_sms": {
            "name": "Send SMS"
        },
        "get_message": {
            "name": "Get metadata of message, such as cost, from, to, and when it was sent."
        }
    },
    "errors": {
        "twilio_error": {
            "name": "Twilio SMS Error"
        },
        "currency_error": {
            "name": "Currency Conversion or Recognition Error"
        }
    }
}

=== OpenGameBackend/OpenGameBackend/modules/captcha/module.json
{
  "name": "Captcha",
  "description": "",
  "icon": "",
  "tags": [],
  "authors": [
    "rivet-gg",
    "ABCxFF"
  ],
  "status": "stable",
  "scripts": {
    "verify_response": {
      "name": "Verify Captcha Response"
    }
  },
  "errors": {
    "captcha_failed": {
      "name": "Captcha Challenge Failed"
    }
  }
}

=== OpenGameBackend/OpenGameBackend/modules/auth/module.json
{
    "name": "Authentication",
    "description": "Authenticate users with multiple authentication methods.",
    "icon": "key",
    "tags": [
        "core",
        "auth",
        "user"
    ],
    "authors": [
        "rivet-gg",
        "NathanFlurry"
    ],
    "status": "stable",
    "dependencies": {
        "email": {},
        "users": {},
        "rate_limit": {}
    },
    "scripts": {
        "send_email_verification": {
            "name": "Send Email Verification",
            "description": "Send a one-time verification code to a user's email address to authenticate them.",
            "public": true
        },
        "complete_email_verification": {
            "name": "Complete Email Verification",
            "description": "Verify a user's email address with a one-time verification code.",
            "public": true
        }
    },
    "errors": {
        "provider_disabled": {
            "name": "Provider Disabled"
        },
        "verification_code_invalid": {
            "name": "Verification Code Invalid"
        },
        "verification_code_attempt_limit": {
            "name": "Verification Code Attempt Limit"
        },
        "verification_code_expired": {
            "name": "Verification Code Expired"
        },
        "verification_code_already_used": {
            "name": "Verification Code Already Used"
        },
        "email_already_used": {
            "name": "Email Already Used"
        }
    }
}

=== OpenGameBackend/OpenGameBackend/modules/auth_email/module.json
{
	"name": "Authentication",
	"description": "Authenticate users with multiple authentication methods.",
	"icon": "key",
	"tags": [
		"core",
		"auth",
		"user"
	],
	"authors": [
		"rivet-gg",
		"NathanFlurry"
	],
	"status": "stable",
	"dependencies": {
		"email": {},
        "identities": {},
        "users": {},
		"tokens": {},
		"user_passwords": {},
		"rate_limit": {}
	},
	"scripts": {
		"send_verification": {
			"name": "Send Email Verification (No Password)",
			"description": "Send a one-time verification code to an email address to verify ownership. Does not require a password.",
			"public": true
		},
		"verify_add_no_pass": {
			"name": "Verify and Add Email to Existing User (No Password)",
			"description": "Verify a user's email address and register it with an existing account. Does not require a password.",
			"public": true
		},
		"verify_login_or_create_no_pass": {
			"name": "Verify and Login as (or Create) User (No Password)",
			"description": "Verify the email address code and return a userToken to AN account (creates a new account if one doesn't exist). Does not require a password.",
			"public": true
		},
		"verify_link_email": {
			"name": "Verify and Link Email Address to User",
			"description": "Verify a user's email address and link it to an existing account without allowing login passwordless.",
			"public": true
		},

		"sign_up_email_pass": {
			"name": "Verify and Sign Up with Email and Password",
			"description": "Sign up a new user with an email and password.",
			"public": true
		},
		"sign_in_email_pass": {
			"name": "Sign In with Email and Password",
			"description": "Sign in a user with an email and password.",
			"public": true
		},
		"verify_add_email_pass": {
			"name": "Verify and Add Email and Password to existing user",
			"description": "Verify a user's email address and register it with an existing account. Requires a password.",
			"public": true
		}
	},
	"errors": {
		"provider_disabled": {
			"name": "Provider Disabled"
		},
		"verification_code_invalid": {
			"name": "Verification Code Invalid"
		},
		"verification_code_attempt_limit": {
			"name": "Verification Code Attempt Limit"
		},
		"verification_code_expired": {
			"name": "Verification Code Expired"
		},
		"verification_code_already_used": {
			"name": "Verification Code Already Used"
		},
		"email_already_used": {
			"name": "Email Already Used"
		}
	}
}
